import type { ZohoBooksPaginatedClient, ZohoBooksModule } from '../../infrastructure/zoho/zoho-books-paginated.client';
import type { CloudinaryAdapter } from '../../infrastructure/cloudinary/cloudinary.adapter';
import type { Logger } from '../../shared/logger';

const DEFAULT_INLINE_THRESHOLD = 25;
const DEFAULT_EXPORT_TTL_SECONDS = 86_400;
const DEFAULT_MAX_PAGES = 20;

export interface ZohoListCsvColumn<T extends Record<string, unknown>> {
  readonly key: string;
  readonly header: string;
  readonly value?: (item: T) => unknown;
}

export interface ListHandlerResult<T extends Record<string, unknown> = Record<string, unknown>> {
  readonly items: T[];
  readonly totalCount: number;
  readonly summary: string;
  readonly csvLink?: string;
  readonly csvPublicId?: string;
  readonly csvExpiresAt?: string;
  readonly truncated: boolean;
  readonly hasMore: boolean;
  readonly suggestExport: boolean;
}

export interface HandleZohoListInput<T extends Record<string, unknown> = Record<string, unknown>> {
  readonly companyId: string;
  readonly userId?: string;
  readonly connectionId?: string;
  readonly organizationId?: string;
  readonly moduleName: ZohoBooksModule;
  readonly moduleLabel: string;
  readonly filters?: Record<string, unknown>;
  readonly query?: string;
  readonly exportAll?: boolean;
  readonly offerExportOnOverflow?: boolean;
  readonly inlineThreshold?: number;
  readonly csvTtlSeconds?: number;
  readonly maxPages?: number;
  readonly fileNameParts?: readonly string[];
  readonly csvColumns: readonly ZohoListCsvColumn<T>[];
  readonly summarize: (items: readonly T[], meta: { truncated: boolean; hasMore: boolean }) => string;
  readonly booksClient: ZohoBooksPaginatedClient;
  readonly cloudinary: CloudinaryAdapter;
  readonly logger: Logger;
}

const toPrimitive = (value: unknown): string | undefined => {
  if (typeof value === 'string' && value.trim().length > 0) return value.trim();
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (typeof value === 'boolean') return String(value);
  return undefined;
};

const escapeCsvCell = (value: unknown): string => {
  const source = String(value ?? '');
  const raw = /^[=+\-@]/.test(source) ? `'${source}` : source;
  if (raw.includes(',') || raw.includes('"') || raw.includes('\n') || raw.includes('\r')) {
    return `"${raw.replace(/"/g, '""')}"`;
  }
  return raw;
};

const safeFilePart = (value: string): string =>
  value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 64);

function buildCsv<T extends Record<string, unknown>>(
  columns: readonly ZohoListCsvColumn<T>[],
  items: readonly T[],
): Buffer {
  const generatedAt = new Date();
  const rows = [
    columns.map(column => escapeCsvCell(column.header)).join(','),
    ...items.map(item =>
      columns.map(column => escapeCsvCell(column.value ? column.value(item) : item[column.key])).join(','),
    ),
    '',
    escapeCsvCell(`Generated by Divo on ${generatedAt.toLocaleString('en-US', {
      month:      'short',
      day:        'numeric',
      year:       'numeric',
      hour:       '2-digit',
      minute:     '2-digit',
      hour12:     false,
      timeZone:   'UTC',
      timeZoneName: 'short',
    })}`),
  ];
  return Buffer.from(rows.join('\n'), 'utf-8');
}

function buildFileName(input: {
  moduleLabel: string;
  companyId: string;
  filters?: Record<string, unknown>;
  query?: string;
  fileNameParts?: readonly string[];
}): string {
  const today = new Date().toISOString().slice(0, 10);
  const filterParts = Object.entries(input.filters ?? {})
    .map(([key, value]) => {
      const primitive = toPrimitive(value);
      return primitive ? `${safeFilePart(key)}-${safeFilePart(primitive)}` : '';
    })
    .filter(Boolean);
  const queryPart = input.query ? [`query-${safeFilePart(input.query)}`] : [];
  const customParts = (input.fileNameParts ?? []).map(safeFilePart).filter(Boolean);
  const parts = [
    'divo',
    safeFilePart(input.moduleLabel),
    ...customParts,
    ...filterParts,
    ...queryPart,
    today,
    input.companyId.slice(0, 8),
  ].filter(Boolean);
  return `${parts.join('-')}.csv`;
}

function appendEscalation(summary: string, moduleLabel: string): string {
  return [
    summary,
    `Found more ${moduleLabel.toLowerCase()} than can fit inline.`,
    'For a full CSV, retry this same tool with top-level exportAll=true; keep op, connectionId, dateFrom/dateTo, and status top-level.',
    'Do not fetch pages manually or use a different storage tool.',
  ].join(' ');
}

export async function handleZohoList<T extends Record<string, unknown> = Record<string, unknown>>(
  input: HandleZohoListInput<T>,
): Promise<ListHandlerResult<T>> {
  const inlineThreshold = input.inlineThreshold ?? DEFAULT_INLINE_THRESHOLD;
  const shouldExhaust = input.exportAll === true;

  const firstPage = await input.booksClient.listRecords({
    companyId:  input.companyId,
    ...(input.userId ? { userId: input.userId } : {}),
    ...(input.connectionId ? { connectionId: input.connectionId } : {}),
    moduleName: input.moduleName,
    ...(input.organizationId ? { organizationId: input.organizationId } : {}),
    ...(input.filters ? { filters: input.filters } : {}),
    ...(input.query ? { query: input.query } : {}),
    page:       1,
    perPage:    Math.max(inlineThreshold, 25),
  });

  const firstItems = firstPage.items as T[];
  if (!shouldExhaust) {
    const visible = firstItems.slice(0, inlineThreshold);
    const hasOverflow = firstPage.hasMore || firstItems.length > inlineThreshold;
    const shouldOfferExport = hasOverflow && input.offerExportOnOverflow !== false;
    const baseSummary = input.summarize(visible, { truncated: false, hasMore: firstPage.hasMore });
    return {
      items: visible,
      totalCount: firstItems.length,
      summary: shouldOfferExport ? appendEscalation(baseSummary, input.moduleLabel) : baseSummary,
      truncated: false,
      hasMore: firstPage.hasMore,
      suggestExport: shouldOfferExport,
    };
  }

  const exhausted = await input.booksClient.listAllRecords({
    companyId:  input.companyId,
    ...(input.userId ? { userId: input.userId } : {}),
    ...(input.connectionId ? { connectionId: input.connectionId } : {}),
    moduleName: input.moduleName,
    ...(input.organizationId ? { organizationId: input.organizationId } : {}),
    ...(input.filters ? { filters: input.filters } : {}),
    ...(input.query ? { query: input.query } : {}),
    maxPages: input.maxPages ?? DEFAULT_MAX_PAGES,
  });

  const allItems = exhausted.items as T[];
  const visible = allItems.slice(0, inlineThreshold);
  let csvLink: string | undefined;
  let csvPublicId: string | undefined;
  let csvExpiresAt: string | undefined;

  if (allItems.length > 0 && input.cloudinary.isAvailable) {
    const fileName = buildFileName({
      moduleLabel: input.moduleLabel,
      companyId: input.companyId,
      ...(input.filters ? { filters: input.filters } : {}),
      ...(input.query ? { query: input.query } : {}),
      ...(input.fileNameParts ? { fileNameParts: input.fileNameParts } : {}),
    });
    const uploaded = await input.cloudinary.uploadCsvBuffer({
      buffer: buildCsv(input.csvColumns, allItems),
      fileName,
      companyId: input.companyId,
      ttlSeconds: input.csvTtlSeconds ?? DEFAULT_EXPORT_TTL_SECONDS,
    });
    if (uploaded) {
      csvLink = uploaded.signedUrl;
      csvPublicId = uploaded.publicId;
      csvExpiresAt = uploaded.expiresAt;
      input.logger.info('zoho.list_handler.csv_exported', {
        companyId: input.companyId,
        moduleName: input.moduleName,
        count: allItems.length,
        fileName,
        expiresAt: csvExpiresAt,
      });
    }
  }

  let summary = input.summarize(allItems, { truncated: exhausted.truncated, hasMore: exhausted.truncated });
  if (allItems.length > inlineThreshold) {
    summary += ` Showing ${visible.length} inline.`;
    summary += csvLink
      ? ' Full dataset is available as a CSV download link.'
      : ' CSV export is unavailable right now, so only the first records are shown inline.';
  } else if (csvLink) {
    summary += ' Full dataset is available as a CSV download link.';
  }
  if (exhausted.truncated) {
    summary += ' Pagination limit reached; additional records may exist beyond the scan window.';
  }

  return {
    items: visible,
    totalCount: allItems.length,
    summary,
    ...(csvLink ? { csvLink } : {}),
    ...(csvPublicId ? { csvPublicId } : {}),
    ...(csvExpiresAt ? { csvExpiresAt } : {}),
    truncated: exhausted.truncated,
    hasMore: exhausted.truncated,
    suggestExport: false,
  };
}
