import vm from 'node:vm';
import { formatAmount, formatDate } from '../../../zoho/zoho-format.utils';

const EXECUTION_TIMEOUT_MS = 5_000;
const MAX_INPUT_BYTES      = 10 * 1024 * 1024;

export class SandboxTimeoutError extends Error {
  constructor() { super('Script timed out after 5 seconds. Simplify the processing logic.'); }
}

export class SandboxScriptError extends Error {
  constructor(cause: string) { super(`Script error: ${cause}`); }
}

export class SandboxInputTooLargeError extends Error {
  constructor(sizeMb: number) { super(`Input data too large (${sizeMb.toFixed(1)} MB). Max is 10 MB.`); }
}

export class SandboxSerializationError extends Error {
  constructor() { super('Script returned a value that cannot be serialized to JSON.'); }
}

export interface SandboxInput {
  readonly script: string;
  readonly data:   unknown;
  readonly args?:  Record<string, unknown> | undefined;
  readonly schema?: Record<string, unknown> | null | undefined;
}

export interface SandboxResult {
  readonly result:   unknown;
  readonly isArray:  boolean;
  readonly rowCount?: number | undefined;
}

export function runInSandbox(input: SandboxInput): SandboxResult {
  const dataStr = JSON.stringify(input.data);
  if (dataStr.length > MAX_INPUT_BYTES) {
    throw new SandboxInputTooLargeError(dataStr.length / 1024 / 1024);
  }

  const sandbox = {
    data:   JSON.parse(dataStr),
    args:   input.args ?? {},
    schema: input.schema ?? null,
    formatAmount,
    formatDate,
    Math, Date, JSON, Array, Object, String, Number, Boolean, RegExp,
    Map, Set, parseInt, parseFloat, isNaN, isFinite,
    console: { log: () => {}, warn: () => {}, error: () => {} },
  };

  const context = vm.createContext(sandbox, {
    codeGeneration: { strings: false, wasm: false },
  });

  let raw: unknown;
  try {
    raw = vm.runInContext(`(function() { ${input.script} })()`, context, {
      timeout: EXECUTION_TIMEOUT_MS,
      filename: 'sandbox.js',
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    if (msg.includes('Script execution timed out')) throw new SandboxTimeoutError();
    throw new SandboxScriptError(msg);
  }

  let serialized: unknown;
  try {
    serialized = JSON.parse(JSON.stringify(raw));
  } catch {
    throw new SandboxSerializationError();
  }

  const isArray  = Array.isArray(serialized);
  const rowCount = isArray ? (serialized as unknown[]).length : undefined;
  return { result: serialized, isArray, rowCount };
}

// ─── CSV helpers ──────────────────────────────────────────────────────────────

function escapeCsvCell(v: unknown): string {
  const s = String(v ?? '');
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

export function arrayToCsv(headers: string[], rows: unknown[]): Buffer {
  const lines: string[] = [headers.map(escapeCsvCell).join(',')];
  for (const row of rows) {
    if (row && typeof row === 'object') {
      const r = row as Record<string, unknown>;
      lines.push(headers.map(h => escapeCsvCell(r[h])).join(','));
    }
  }
  lines.push('');
  lines.push(`Generated by Divo on ${new Date().toISOString()}`);
  return Buffer.from(lines.join('\n'), 'utf-8');
}
