import type { EmployeesListResponse } from "./types";

export const MOCK_EMPLOYEES_RESPONSE: EmployeesListResponse = {
  company_id: "company_hermes",
  members: [
    {
      id: "cu_alice",
      company_id: "company_hermes",
      display_name: "Alice Example",
      email: "alice@example.com",
      avatar_url: null,
      lark_open_id: "ou_alice_open",
      lark_union_id: "on_alice_union",
      lark_user_id: null,
      department_id: "dept_engineering",
      department_name: "Engineering",
      role: "COMPANY_ADMIN",
      status: "active",
      first_login_at: "2026-05-01T09:15:00+00:00",
      last_login_at: "2026-06-12T08:42:00+00:00",
      provider: "lark",
    },
    {
      id: "cu_bob",
      company_id: "company_hermes",
      display_name: "Bob Chen",
      email: "bob@example.com",
      avatar_url: null,
      lark_open_id: "ou_bob_open",
      lark_union_id: "on_bob_union",
      lark_user_id: "4g7b2c1d",
      department_id: "dept_engineering",
      department_name: "Engineering",
      role: "MEMBER",
      status: "active",
      first_login_at: "2026-05-14T11:00:00+00:00",
      last_login_at: "2026-06-11T17:20:00+00:00",
      provider: "lark",
    },
    {
      id: "cu_carla",
      company_id: "company_hermes",
      display_name: "Carla Singh",
      email: "carla@example.com",
      avatar_url: null,
      lark_open_id: "ou_carla_open",
      lark_union_id: null,
      lark_user_id: null,
      department_id: "dept_ops",
      department_name: "Operations",
      role: "MEMBER",
      status: "active",
      first_login_at: "2026-05-20T14:30:00+00:00",
      last_login_at: "2026-06-10T09:05:00+00:00",
      provider: "lark",
    },
    {
      id: "cu_dan",
      company_id: "company_hermes",
      display_name: "Dan Park",
      email: "dan@example.com",
      avatar_url: null,
      lark_open_id: "ou_dan_open",
      lark_union_id: "on_dan_union",
      lark_user_id: null,
      department_id: "dept_ops",
      department_name: "Operations",
      role: "MEMBER",
      status: "disabled",
      first_login_at: "2026-04-02T10:00:00+00:00",
      last_login_at: "2026-05-28T16:45:00+00:00",
      provider: "lark",
    },
    {
      id: "cu_eve",
      company_id: "company_hermes",
      display_name: "Eve Martinez",
      email: null,
      avatar_url: null,
      lark_open_id: "ou_eve_open",
      lark_union_id: "on_eve_union",
      lark_user_id: null,
      department_id: null,
      department_name: null,
      role: "MEMBER",
      status: "invited",
      first_login_at: null,
      last_login_at: null,
      provider: "lark",
    },
    {
      id: "cu_frank",
      company_id: "company_hermes",
      display_name: "Frank Okonkwo",
      email: "frank@example.com",
      avatar_url: null,
      lark_open_id: "ou_frank_open",
      lark_union_id: null,
      lark_user_id: "9a2f88e1",
      department_id: "dept_finance",
      department_name: "Finance",
      role: "MEMBER",
      status: "active",
      first_login_at: "2026-06-01T08:00:00+00:00",
      last_login_at: "2026-06-12T07:10:00+00:00",
      provider: "lark",
    },
    {
      id: "cu_grace",
      company_id: "company_hermes",
      display_name: "Grace Kim",
      email: "grace@example.com",
      avatar_url: null,
      lark_open_id: "ou_grace_open",
      lark_union_id: "on_grace_union",
      lark_user_id: null,
      department_id: "dept_finance",
      department_name: "Finance",
      role: "SUPER_ADMIN",
      status: "active",
      first_login_at: "2026-03-15T12:00:00+00:00",
      last_login_at: "2026-06-12T06:55:00+00:00",
      provider: "lark",
    },
    {
      id: "cu_henry",
      company_id: "company_hermes",
      display_name: "Henry Wright",
      email: "henry@example.com",
      avatar_url: null,
      lark_open_id: null,
      lark_union_id: null,
      lark_user_id: null,
      department_id: "dept_engineering",
      department_name: "Engineering",
      role: "MEMBER",
      status: "active",
      first_login_at: "2026-06-08T13:22:00+00:00",
      last_login_at: "2026-06-09T13:22:00+00:00",
      provider: "lark",
    },
  ],
};
