/**
 * dataProcessor tool — sandboxed JavaScript execution for data transformation.
 *
 * Two modes:
 *   1. Direct data: LLM passes `data` array from a previous tool call (small datasets)
 *   2. Zoho fetch + process: LLM passes `zohoSource` describing what to fetch from Zoho Books.
 *      The tool fetches ALL records internally (exhaustive pagination), then runs the script.
 *      The LLM never sees the raw dataset — only the processed result.
 *
 * The script runs in a Node.js `vm` sandbox with no filesystem, network, or process access.
 * 5-second timeout, 10 MB data limit.
 */

import vm from 'node:vm';
import { z } from 'zod';
import type { Tool, ToolExecutionContext } from '../tool.contract';
import type { Result } from '../../../../shared/result';
import { ok, err } from '../../../../shared/result';
import { PermissionError, ToolError } from '../../../../shared/errors';
import type { ToolActionGroup } from '../../../../domain/permissions/tool-action-group';
import { asToolId } from '../../../../shared/ids';
import type { CloudinaryAdapter } from '../../../../infrastructure/cloudinary/cloudinary.adapter';
import type { ZohoBooksPaginatedClient, ZohoBooksModule } from '../../../../infrastructure/zoho/zoho-books-paginated.client';
import { formatAmount, formatDate } from '../../../zoho/zoho-format.utils';

const EXECUTION_TIMEOUT_MS = 5_000;
const MAX_INPUT_BYTES = 10 * 1024 * 1024;
const INLINE_RESULT_LIMIT = 50;

const zohoSourceSchema = z.object({
  module: z.string().describe('Zoho Books module: invoices, bills, expenses, contacts, customerpayments, bankaccounts, banktransactions, items, etc.'),
  filters: z.record(z.unknown()).optional().describe(
    'Zoho API filters. For "status", pass a single value OR comma-separated values (e.g. "sent,overdue") — the tool splits and merges automatically. ' +
    'Invoice status values: draft, sent, overdue, paid, void, partially_paid, viewed. ' +
    'Bill status values: open, paid, overdue, void. ' +
    'Example: { status: "sent,overdue", from_date: "2025-04-01", to_date: "2026-03-31" }',
  ),
  query: z.string().optional().describe('Search query string'),
}).describe('Fetch ALL records from a Zoho Books module (exhaustive pagination, up to 4000 records). The tool fetches the data internally — the LLM never sees the raw records.');

const Schema = z.object({
  script: z.string().describe(
    'JavaScript code to execute. Receives `data` (array) and `args` (object). Must return the result. Example: "const grouped = {}; for (const b of data) { const v = b.vendor_name || \'Unknown\'; if (!grouped[v]) grouped[v] = { vendor: v, count: 0, total: 0 }; grouped[v].count++; grouped[v].total += b.total || 0; } return Object.values(grouped).sort((a,b) => b.count - a.count)"',
  ),
  data: z.unknown().optional().describe(
    'Direct data to process (small datasets from a previous tool call). Omit this when using zohoSource.',
  ),
  zohoSource: zohoSourceSchema.optional().describe(
    'Fetch data from Zoho Books before processing. When set, the tool fetches ALL records internally (exhaustive pagination) then runs the script on them. Use this for large datasets — the LLM only sees the processed result, not the raw records.',
  ),
  args: z.record(z.unknown()).optional().describe(
    'Optional extra parameters for the script (e.g. { minAmount: 1000, groupBy: "vendor_name" }).',
  ),
  exportCsv: z.boolean().optional().describe(
    'If true and result is an array, export as CSV to Cloudinary and return a download link.',
  ),
  csvColumns: z.array(z.string()).optional().describe(
    'Column order for CSV export. If not provided, uses all keys from first result row.',
  ),
});

type Args = z.infer<typeof Schema>;

const ResultSchema = z.object({
  success: z.boolean(),
  data: z.unknown().optional(),
  rowCount: z.number().optional(),
  totalFetched: z.number().optional(),
  message: z.string().optional(),
  csvLink: z.string().optional(),
  csvExpiresAt: z.string().optional(),
});

type Res = z.infer<typeof ResultSchema>;

function escapeCsvCell(v: unknown): string {
  const s = String(v ?? '');
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function arrayToCsv(headers: string[], rows: unknown[]): Buffer {
  const lines: string[] = [headers.map(escapeCsvCell).join(',')];
  for (const row of rows) {
    if (row && typeof row === 'object') {
      const r = row as Record<string, unknown>;
      lines.push(headers.map(h => escapeCsvCell(r[h])).join(','));
    }
  }
  lines.push('');
  lines.push(`Generated by Divo on ${new Date().toISOString()}`);
  return Buffer.from(lines.join('\n'), 'utf-8');
}

export const createDataProcessorTool = (deps: {
  cloudinary: CloudinaryAdapter;
  booksClient: ZohoBooksPaginatedClient;
  csvLinkTtl?: number;
}): Tool<Args, Res> => ({
  id: asToolId('dataProcessor'),
  family: 'data',
  actionGroups: new Set(['read']),
  argsSchema: Schema,
  resultSchema: ResultSchema,

  description: [
    'Process and transform data using a sandboxed JavaScript script.',
    'Two modes: (1) pass data directly for small datasets, (2) set zohoSource to fetch ALL records from a Zoho Books module internally (exhaustive pagination, up to 4000 records) then process.',
    'Use zohoSource for grouping/aggregation/analysis queries — the tool fetches the complete dataset, runs your script, and returns only the processed result.',
    'The script receives `data` (array) and `args` (object). It must return a value.',
    'Set exportCsv=true to get a downloadable CSV of the processed result.',
  ].join(' '),

  parameterDocs: [
    'script: JS code. Receives `data` (array) and `args` (object). Must `return` a value.',
    '  Example: "const grouped = {}; for (const b of data) { const v = b.vendor_name; if (!grouped[v]) grouped[v] = { vendor: v, count: 0, total: 0 }; grouped[v].count++; grouped[v].total += b.total || 0; } return Object.values(grouped).sort((a,b) => b.count - a.count)"',
    '',
    'zohoSource: { module: "bills", filters: { from_date: "2025-04-01", to_date: "2026-03-31" } }',
    '  Fetches ALL records from the specified Zoho Books module with filters.',
    '  Supported modules: invoices, bills, expenses, contacts, customerpayments, bankaccounts, banktransactions, items',
    '  The fetched records become `data` in the script. You do NOT need to call zohoBooks separately.',
    '',
    'data: pass directly for small datasets (< 100 items). Omit when using zohoSource.',
    'args: optional extra parameters for the script',
    'exportCsv: true to upload processed result as CSV and return download link',
    'csvColumns: column order for CSV (optional, auto-detected if omitted)',
  ].join('\n'),

  permissionCheck(_args, perm) {
    const allowed = perm.allowedToolIds.has(asToolId('dataProcessor'));
    return allowed
      ? ok('read' as ToolActionGroup)
      : err(new PermissionError({ toolId: 'dataProcessor', action: 'read', reason: 'not_allowed' }));
  },

  async execute(args: Args, ctx: ToolExecutionContext): Promise<Result<Res, ToolError>> {
    const { companyId } = ctx.runContext;

    // ── Resolve input data ─────────────────────────────────────────────────
    let inputData: unknown;
    let totalFetched: number | undefined;

    if (args.zohoSource) {
      // Fetch from Zoho Books internally — LLM never sees the raw records
      ctx.logger.info('data_processor.zoho_fetch.start', {
        companyId,
        module: args.zohoSource.module,
        filters: args.zohoSource.filters,
        query: args.zohoSource.query,
      });

      try {
        const result = await deps.booksClient.listAllRecords({
          companyId,
          moduleName: args.zohoSource.module as ZohoBooksModule,
          ...(args.zohoSource.filters ? { filters: args.zohoSource.filters as Record<string, string> } : {}),
          ...(args.zohoSource.query ? { query: args.zohoSource.query } : {}),
        });

        inputData = result.items;
        totalFetched = result.items.length;

        ctx.logger.info('data_processor.zoho_fetch.done', {
          companyId,
          module: args.zohoSource.module,
          recordsFetched: totalFetched,
          truncated: result.truncated,
        });
      } catch (e) {
        ctx.logger.error('data_processor.zoho_fetch.failed', {
          companyId,
          module: args.zohoSource.module,
          error: e instanceof Error ? e.message : String(e),
        });
        return err(new ToolError({
          toolId: 'dataProcessor',
          reason: 'upstream_failure',
          message: `Failed to fetch ${args.zohoSource.module} from Zoho Books: ${e instanceof Error ? e.message : String(e)}`,
        }));
      }
    } else if (args.data !== undefined) {
      inputData = args.data;
    } else {
      return err(new ToolError({
        toolId: 'dataProcessor',
        reason: 'bad_args',
        message: 'Either data or zohoSource must be provided.',
      }));
    }

    // ── Input size guard ───────────────────────────────────────────────────
    const dataStr = JSON.stringify(inputData);
    if (dataStr.length > MAX_INPUT_BYTES) {
      return err(new ToolError({
        toolId: 'dataProcessor',
        reason: 'bad_args',
        message: `Input data too large (${(dataStr.length / 1024 / 1024).toFixed(1)} MB). Max is 10 MB.`,
      }));
    }

    ctx.logger.info('data_processor.execute', {
      companyId,
      scriptLength: args.script.length,
      dataSize: dataStr.length,
      dataRecords: Array.isArray(inputData) ? inputData.length : 'non-array',
      hasArgs: !!args.args,
      exportCsv: args.exportCsv ?? false,
      source: args.zohoSource ? 'zoho_fetch' : 'direct',
    });

    // ── Build sandbox ──────────────────────────────────────────────────────
    const sandbox = {
      data: JSON.parse(dataStr),
      args: args.args ?? {},
      formatAmount,
      formatDate,
      Math,
      Date,
      JSON,
      Array,
      Object,
      String,
      Number,
      Boolean,
      RegExp,
      Map,
      Set,
      parseInt,
      parseFloat,
      isNaN,
      isFinite,
      console: { log: () => {}, warn: () => {}, error: () => {} },
    };

    const context = vm.createContext(sandbox, {
      codeGeneration: { strings: false, wasm: false },
    });

    // ── Execute script ─────────────────────────────────────────────────────
    let result: unknown;
    try {
      const wrappedScript = `(function() { ${args.script} })()`;
      result = vm.runInContext(wrappedScript, context, {
        timeout: EXECUTION_TIMEOUT_MS,
        filename: 'data-processor-sandbox.js',
      });
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      ctx.logger.warn('data_processor.script_error', { companyId, error: message });

      if (message.includes('Script execution timed out')) {
        return err(new ToolError({
          toolId: 'dataProcessor',
          reason: 'upstream_failure',
          message: 'Script timed out after 5 seconds. Simplify the processing logic.',
        }));
      }

      return err(new ToolError({
        toolId: 'dataProcessor',
        reason: 'upstream_failure',
        message: `Script error: ${message}`,
      }));
    }

    // ── Serialize result ───────────────────────────────────────────────────
    let serialized: unknown;
    try {
      serialized = JSON.parse(JSON.stringify(result));
    } catch {
      return err(new ToolError({
        toolId: 'dataProcessor',
        reason: 'upstream_failure',
        message: 'Script returned a value that cannot be serialized to JSON.',
      }));
    }

    const serializedArray = Array.isArray(serialized) ? serialized as unknown[] : null;
    const rowCount = serializedArray?.length;

    ctx.logger.info('data_processor.result', {
      companyId,
      isArray: !!serializedArray,
      rowCount,
      resultSize: JSON.stringify(serialized).length,
      source: args.zohoSource ? 'zoho_fetch' : 'direct',
    });

    // ── CSV export ─────────────────────────────────────────────────────────
    let csvLink: string | undefined;
    let csvExpiresAt: string | undefined;

    if (args.exportCsv && serializedArray && serializedArray.length > 0 && deps.cloudinary.isAvailable) {
      try {
        const firstRow = serializedArray[0] as Record<string, unknown>;
        const columns = args.csvColumns ?? Object.keys(firstRow);
        const csvBuffer = arrayToCsv(columns, serializedArray);
        const dateStr = new Date().toISOString().slice(0, 10);
        const fileName = `divo-export-${dateStr}-${companyId.slice(0, 8)}.csv`;

        const exported = await deps.cloudinary.uploadCsvBuffer({
          buffer: csvBuffer,
          fileName,
          companyId,
          ttlSeconds: deps.csvLinkTtl ?? 86_400,
        });

        if (exported) {
          csvLink = exported.signedUrl;
          csvExpiresAt = exported.expiresAt;
          ctx.logger.info('data_processor.csv_exported', { companyId, fileName, rows: serializedArray.length });
        }
      } catch (e) {
        ctx.logger.warn('data_processor.csv_failed', { companyId, error: String(e) });
      }
    }

    // ── Response ───────────────────────────────────────────────────────────
    const inlineData = serializedArray && serializedArray.length > INLINE_RESULT_LIMIT
      ? serializedArray.slice(0, INLINE_RESULT_LIMIT)
      : serialized;

    const parts: string[] = [];
    if (totalFetched !== undefined) parts.push(`Fetched ${totalFetched} records from Zoho Books.`);
    if (serializedArray) {
      parts.push(`Processed into ${serializedArray.length} rows.`);
      if (serializedArray.length > INLINE_RESULT_LIMIT) parts.push(`Showing first ${INLINE_RESULT_LIMIT} inline.`);
    } else {
      parts.push('Processing complete.');
    }
    if (csvLink) parts.push('Full CSV available via download link.');

    return ok({
      success: true,
      data: inlineData,
      rowCount,
      totalFetched,
      message: parts.join(' '),
      ...(csvLink ? { csvLink } : {}),
      ...(csvExpiresAt ? { csvExpiresAt } : {}),
    });
  },
});
