import type { ToolActionGroup } from './tool-action-groups';

export type ToolCategory = 'crm-read' | 'crm-action' | 'search' | 'workspace' | 'routing';

/** Built-in role slugs (always present for every company). */
export type AiRole = 'MEMBER' | 'COMPANY_ADMIN' | 'SUPER_ADMIN';
export const BUILT_IN_ROLES: AiRole[] = ['MEMBER', 'COMPANY_ADMIN', 'SUPER_ADMIN'];

export interface ToolDefinition {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  /** Which engine(s) implement this tool. */
  engines: ('legacy' | 'vercel')[];
  /** Default permission for built-in roles; custom roles default to same as MEMBER. */
  defaultPermissions: Record<AiRole, boolean>;
  supportedActionGroups?: ToolActionGroup[];
}

export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: 'repo',
    name: 'Repository Inspector',
    description: 'Inspect remote GitHub repositories and retrieve repository files.',
    category: 'search',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'coding',
    name: 'Coding Workspace Tool',
    description: 'Plan and verify local workspace coding tasks that may require approved file or terminal actions.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'skill-search',
    name: 'Skill Search',
    description: 'Search and read reusable global and department skills for specialized workflows.',
    category: 'search',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'google-gmail',
    name: 'Google Gmail',
    description: 'List, read, draft, and send Gmail messages using the connected Google account.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'List, read, download, and upload Google Drive files using the connected account.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'List, read, create, update, and delete Google Calendar events using the connected account.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'document-ocr-read',
    name: 'Document OCR Read',
    description: 'List accessible uploaded files and extract machine-readable text from PDFs, docs, and scanned images.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'invoice-parser',
    name: 'Invoice Parser',
    description: 'Parse uploaded invoice and bill documents into structured finance fields.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'statement-parser',
    name: 'Statement Parser',
    description: 'Parse uploaded bank and account statements into structured rows and totals.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'search-zoho-context',
    name: 'Search Zoho Context',
    description: 'Search indexed Zoho CRM records (deals, contacts, tickets) from the vector database.',
    category: 'crm-read',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'read-zoho-records',
    name: 'Read Zoho Records',
    description: 'Fetch formatted Zoho CRM data with risk analysis, health reports, and pipeline summaries.',
    category: 'crm-read',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'zoho-agent',
    name: 'Zoho CRM Agent',
    description: 'Delegate to the Zoho CRM specialist agent for deep CRM data queries.',
    category: 'crm-read',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'zoho-write',
    name: 'Zoho CRM Write',
    description: 'Create, update, and delete Zoho CRM records, notes, and attachments after human approval.',
    category: 'crm-action',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'zoho-books-read',
    name: 'Zoho Books Read',
    description: 'Read Zoho Books finance records, contacts, vendor payments, bank accounts, credit notes, sales orders, purchase orders, bank transaction match suggestions, and related invoice/email/statement metadata.',
    category: 'crm-read',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'zoho-books-write',
    name: 'Zoho Books Write',
    description: 'Create, update, delete, reconcile, categorize, email, remind, import, and status-change Zoho Books records after human approval.',
    category: 'crm-action',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'zoho-books-agent',
    name: 'Zoho Books Agent',
    description: 'Delegate to the Zoho Books specialist workflow for finance operations.',
    category: 'crm-read',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'read-outreach-publishers',
    name: 'Read Outreach Publishers',
    description:
      'Fetch outreach publisher inventory using structured filters such as client URL, DA/DR, country, and pricing.',
    category: 'search',
    engines: ['legacy', 'vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'outreach-agent',
    name: 'Outreach Agent',
    description:
      'Delegate to the outreach specialist agent for publisher filtering and SEO inventory queries.',
    category: 'search',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'search-agent',
    name: 'Search Agent',
    description: 'Delegate to the research agent for external web research, exact-site page context, and internal document retrieval.',
    category: 'search',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'search-read',
    name: 'Web Search Read',
    description: 'Search the web via Serper, then fetch result pages to extract page context.',
    category: 'search',
    engines: ['legacy', 'vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'search-documents',
    name: 'Search Documents',
    description: 'Search uploaded company documents and private knowledge chunks that the requester is authorized to access.',
    category: 'search',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-base-read',
    name: 'Lark Base Read',
    description: 'List records from Lark Base / Bitable tables.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-base-write',
    name: 'Lark Base Write',
    description: 'Create or update records in Lark Base / Bitable tables.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-base-agent',
    name: 'Lark Base Agent',
    description: 'Delegate to the Lark Base specialist for Base record workflows.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-task-read',
    name: 'Lark Task Read',
    description: 'List tasks from Lark Tasks, fetch a specific task, or resolve the current task.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-task-write',
    name: 'Lark Task Write',
    description: 'Create, update, or delete tasks in Lark Tasks.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-task-agent',
    name: 'Lark Task Agent',
    description: 'Delegate to the Lark Tasks specialist for task workflows.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-calendar-list',
    name: 'Lark Calendar List',
    description: 'List available Lark calendars and resolve calendar names to calendar IDs.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-calendar-read',
    name: 'Lark Calendar Read',
    description: 'List events from a Lark Calendar.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-calendar-write',
    name: 'Lark Calendar Write',
    description: 'Create, update, or delete events in a Lark Calendar.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-calendar-agent',
    name: 'Lark Calendar Agent',
    description: 'Delegate to the Lark Calendar specialist for scheduling and calendar workflows.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-meeting-read',
    name: 'Lark Meeting Read',
    description: 'List meetings, fetch one meeting, or fetch a Lark minute.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-meeting-agent',
    name: 'Lark Meeting Agent',
    description: 'Delegate to the Lark Meetings specialist for meeting lookup and minute retrieval.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-approval-read',
    name: 'Lark Approval Read',
    description: 'List or fetch Lark approval instances.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-approval-write',
    name: 'Lark Approval Write',
    description: 'Create a Lark approval instance.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-approval-agent',
    name: 'Lark Approval Agent',
    description: 'Delegate to the Lark Approvals specialist for approval workflows.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'create-lark-doc',
    name: 'Create Lark Doc',
    description: 'Create a new Lark Doc from grounded content in the current conversation.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'edit-lark-doc',
    name: 'Edit Lark Doc',
    description: 'Edit the latest or specified Lark Doc by appending, replacing, patching, or deleting sections.',
    category: 'workspace',
    engines: ['vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-doc-agent',
    name: 'Lark Doc Agent',
    description: 'Create and edit Lark Docs from grounded content and reports.',
    category: 'workspace',
    engines: ['legacy', 'vercel'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'zoho-read',
    name: 'Zoho Read',
    description: 'Live Zoho CRM read via MCP or REST with vector augmentation.',
    category: 'crm-read',
    engines: ['legacy', 'vercel'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'zoho-action',
    name: 'Zoho Action',
    description: 'Execute write/mutate operations on Zoho CRM. Requires human confirmation.',
    category: 'crm-action',
    engines: ['legacy'],
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'response',
    name: 'Response Agent',
    description: 'Handles greetings and capability questions with low-latency direct replies.',
    category: 'routing',
    engines: ['legacy'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'risk-check',
    name: 'Risk Check',
    description: 'Classifies destructive intent in user messages before action execution.',
    category: 'routing',
    engines: ['legacy'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'lark-response',
    name: 'Lark Responder',
    description: 'Sends progress update messages to Lark channel during task execution.',
    category: 'routing',
    engines: ['legacy'],
    defaultPermissions: { MEMBER: true, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
  {
    id: 'share_chat_vectors',
    name: 'Share Chat Knowledge',
    description:
      'Allows a user to promote their personal conversation vectors to company-wide shared context. ' +
      'When enabled, a "Share this chat\'s knowledge" button will appear on bot responses.',
    category: 'workspace',
    engines: ['vercel'],
    // Off for regular members by default; grant explicitly via the Permissions UI.
    defaultPermissions: { MEMBER: false, COMPANY_ADMIN: true, SUPER_ADMIN: true },
  },
];

export const TOOL_REGISTRY_MAP = new Map(TOOL_REGISTRY.map((t) => [t.id, t]));

/** Map from legacy agent key → toolId in the registry */
export const LEGACY_AGENT_TOOL_MAP: Record<string, string> = {
  'zoho-read': 'zoho-read',
  'zoho-action': 'zoho-action',
  'outreach-read': 'read-outreach-publishers',
  'search-read': 'search-read',
  'lark-doc': 'lark-doc-agent',
  response: 'response',
  'risk-check': 'risk-check',
  'lark-response': 'lark-response',
};
