/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/divo.theme.ts
 * Command: astryx theme build src/styles/divo.theme.ts
 * Generated: 2026-07-20T23:19:59.284Z
 */

/**
 * divo theme — built by `yarn astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { divoTheme } from './divo';
 *   import './divo.css';
 */
export const divoTheme = {
  name: 'divo',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#f17455, #ff8d6d)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #6E0000)",
    "--color-neutral": "light-dark(#0000001a, #ffffff1a)",
    "--color-background-surface": "light-dark(#ffffff, #1f1f1f)",
    "--color-background-body": "light-dark(#ffffff, #181818)",
    "--color-overlay": "light-dark(#00000066, #00000099)",
    "--color-overlay-hover": "light-dark(#0000000d, #ffffff0d)",
    "--color-overlay-pressed": "light-dark(#0000001a, #ffffff1a)",
    "--color-background-muted": "light-dark(#f4f4f5, #262626)",
    "--color-text-primary": "light-dark(#1a1c1f, #ededed)",
    "--color-text-secondary": "light-dark(#818284, #9b9b9b)",
    "--color-text-disabled": "light-dark(#9C8E8A, #685C58)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#1a1c1f, #ededed)",
    "--color-icon-secondary": "light-dark(#504441, #B7A8A4)",
    "--color-icon-disabled": "light-dark(#9C8E8A, #685C58)",
    "--color-background-card": "light-dark(#ffffff, #1f1f1f)",
    "--color-background-popover": "light-dark(#ffffff, #242424)",
    "--color-background-inverted": "light-dark(#1a1c1f, #ededed)",
    "--color-border": "light-dark(#e4e4e5, #ffffff12)",
    "--color-border-emphasized": "light-dark(#B7A8A4, #504441)",
    "--color-skeleton": "light-dark(#B7A8A4, #504441)",
    "--color-track": "light-dark(#B7A8A4, #504441)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)"
  },

};
