/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/divo.theme.ts
 * Command: astryx theme build src/styles/divo.theme.ts
 * Generated: 2026-07-20T23:19:59.284Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const divoTheme: DefinedTheme;
