server {
  listen 80;
  listen [::]:80;
  server_name app.103.172.92.187.sslip.io;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}
