/**
 * Where a conversation's videos live while Divo is reading them, and where the
 * reading lives afterwards.
 *
 * One directory per video, holding at most three things: the recording, the
 * frames taken from it, and the understanding written out as JSON. The
 * recording is deleted the moment the understanding exists — we are not a video
 * store, and nothing reads the bytes again once they have been read once.
 *
 * On local disk, like Teach's evidence before it. That carries Teach's existing
 * constraint with it: the process that writes and the process that reads must
 * share a filesystem. Stated here rather than discovered later.
 */

import { createWriteStream } from 'node:fs';
import { mkdir, readFile, readdir, rename, rm, stat, writeFile } from 'node:fs/promises';
import { pipeline } from 'node:stream/promises';
import { Transform, type Readable } from 'node:stream';
import { isAbsolute, join, resolve } from 'node:path';
import type { VideoUnderstanding } from '../video-understanding/video-understanding.types';

/** Who a video belongs to, so one person cannot read another's reading. */
export interface ConversationVideoOwner {
  readonly companyId: string;
  readonly userId: string;
  readonly channel: string;
  readonly threadId: string;
}

export interface ConversationVideoRecord extends ConversationVideoOwner {
  readonly videoId: string;
  readonly fileName: string;
  readonly mimeType: string;
  readonly sizeBytes: number;
  readonly receivedAt: string;
}

export class ConversationVideoTooLargeError extends Error {
  constructor(limitBytes: number) {
    super(`The video exceeds the ${Math.floor(limitBytes / 1_048_576)} MB upload limit`);
    this.name = 'ConversationVideoTooLargeError';
  }
}

const META = 'meta.json';
const UNDERSTANDING = 'understanding.json';
const FRAMES = 'frames';

/**
 * Ids are generated by us and only ever used as one path segment, but they
 * arrive back from a browser before they are used to build a path. A shape
 * check here is cheaper than trusting every caller to have done one.
 */
const SAFE_ID = /^[a-f0-9-]{36}$/;

export class ConversationVideoStore {
  private readonly root: string;
  /** The most one upload may occupy. Read by the budget as its worst case. */
  readonly maxBytes: number;

  constructor(deps: { readonly rootDir: string; readonly maxBytes: number }) {
    this.root = resolve(deps.rootDir);
    this.maxBytes = deps.maxBytes;
  }

  /**
   * Stream a recording to disk, refusing it the moment it grows past the limit.
   *
   * Counted while streaming rather than trusting `content-length`: the header
   * is a claim by the client, and a body that keeps coming after it has to stop
   * somewhere that is not the disk filling up.
   */
  async saveSource(input: {
    readonly record: ConversationVideoRecord;
    readonly body: Readable;
  }): Promise<number> {
    const dir = this.directoryFor(input.record.companyId, input.record.videoId);
    await mkdir(dir, { recursive: true });
    const target = join(dir, this.sourceName(input.record.mimeType));
    const partial = `${target}.uploading`;

    let received = 0;
    const limit = new Transform({
      transform: (chunk: Buffer, _encoding, callback) => {
        received += chunk.length;
        if (received > this.maxBytes) {
          callback(new ConversationVideoTooLargeError(this.maxBytes));
          return;
        }
        callback(null, chunk);
      },
    });

    try {
      await pipeline(input.body, limit, createWriteStream(partial, { flags: 'w', mode: 0o600 }));
      await rename(partial, target);
    } catch (error) {
      await rm(dir, { recursive: true, force: true });
      throw error;
    }

    await writeFile(
      join(dir, META),
      JSON.stringify({ ...input.record, sizeBytes: received }, null, 2),
      { encoding: 'utf8', mode: 0o600 },
    );
    return received;
  }

  /**
   * How much this company is already holding, in bytes.
   *
   * Counted from disk rather than tracked in memory: the sweep, a crash and a
   * restart all change it without going through this process, and a counter
   * that drifts either refuses uploads that would have fit or lets through the
   * ones this is here to stop.
   */
  async bytesHeldBy(companyId: string): Promise<number> {
    // Recursive, because the extracted stills live in a `frames/` subdirectory
    // and are the larger half of what a read video leaves behind.
    return this.bytesUnder(join(this.root, companyId));
  }

  private async bytesUnder(dir: string): Promise<number> {
    let total = 0;
    for (const name of await this.safeReaddir(dir)) {
      const path = join(dir, name);
      try {
        const metadata = await stat(path);
        if (metadata.isDirectory()) total += await this.bytesUnder(path);
        else if (metadata.isFile()) total += metadata.size;
      } catch { /* raced with the sweep */ }
    }
    return total;
  }

  /** Everything every company is holding, for the deployment-wide ceiling. */
  async bytesHeldInTotal(): Promise<number> {
    return this.bytesUnder(this.root);
  }

  async metaFor(companyId: string, videoId: string): Promise<ConversationVideoRecord | null> {
    try {
      const raw = await readFile(join(this.directoryFor(companyId, videoId), META), 'utf8');
      return JSON.parse(raw) as ConversationVideoRecord;
    } catch {
      return null;
    }
  }

  /** The recording, or null once it has been read and thrown away. */
  async sourcePath(companyId: string, videoId: string, mimeType: string): Promise<string | null> {
    const path = join(this.directoryFor(companyId, videoId), this.sourceName(mimeType));
    try {
      const metadata = await stat(path);
      return metadata.isFile() ? path : null;
    } catch {
      return null;
    }
  }

  framesDir(companyId: string, videoId: string): string {
    return join(this.directoryFor(companyId, videoId), FRAMES);
  }

  /**
   * Write the reading, then delete the recording.
   *
   * That order, always: a crash between the two leaves a video that will be
   * read again, which is wasteful. The other order leaves a question that can
   * never be answered, which is a lie about what Divo kept.
   */
  async commitUnderstanding(
    companyId: string,
    videoId: string,
    understanding: VideoUnderstanding,
  ): Promise<void> {
    const dir = this.directoryFor(companyId, videoId);
    const target = join(dir, UNDERSTANDING);
    const partial = `${target}.tmp`;
    await writeFile(partial, JSON.stringify(understanding), { encoding: 'utf8', mode: 0o600 });
    await rename(partial, target);
    await this.deleteSources(dir);
  }

  async readUnderstanding(companyId: string, videoId: string): Promise<VideoUnderstanding | null> {
    try {
      const raw = await readFile(join(this.directoryFor(companyId, videoId), UNDERSTANDING), 'utf8');
      return JSON.parse(raw) as VideoUnderstanding;
    } catch {
      return null;
    }
  }

  async forget(companyId: string, videoId: string): Promise<void> {
    await rm(this.directoryFor(companyId, videoId), { recursive: true, force: true });
  }

  /**
   * Drop everything older than the retention window.
   *
   * Directory mtime rather than the recorded time: the meta file may be absent
   * on a half-written upload, and a sweep that skips what it cannot parse would
   * never clean up exactly the failures worth cleaning up.
   */
  async prune(olderThanMs: number, now = Date.now()): Promise<number> {
    let removed = 0;
    for (const company of await this.safeReaddir(this.root)) {
      const companyDir = join(this.root, company);
      for (const videoId of await this.safeReaddir(companyDir)) {
        const dir = join(companyDir, videoId);
        try {
          const metadata = await stat(dir);
          // Clamped at zero because the two clocks do not agree to the same
          // precision: `Date.now()` is whole milliseconds and `mtimeMs` carries
          // a fraction, so a directory written inside the current millisecond
          // reads as very slightly in the future. Left unclamped, a negative age
          // is below every window and such a directory is never swept.
          const ageMs = Math.max(0, now - metadata.mtimeMs);
          if (ageMs < olderThanMs) continue;
          await rm(dir, { recursive: true, force: true });
          removed += 1;
        } catch { /* raced with another sweep or a delete; nothing to do */ }
      }
    }
    return removed;
  }

  private async safeReaddir(dir: string): Promise<string[]> {
    try {
      return await readdir(dir);
    } catch {
      return [];
    }
  }

  private async deleteSources(dir: string): Promise<void> {
    for (const name of await this.safeReaddir(dir)) {
      if (name.startsWith('source.')) await rm(join(dir, name), { force: true });
    }
  }

  private sourceName(mimeType: string): string {
    return `source.${extensionForVideoMime(mimeType)}`;
  }

  private directoryFor(companyId: string, videoId: string): string {
    if (!SAFE_ID.test(videoId)) throw new Error('Invalid video id');
    if (!companyId || companyId.includes('/') || companyId.includes('..') || isAbsolute(companyId)) {
      throw new Error('Invalid company id');
    }
    return join(this.root, companyId, videoId);
  }
}

/**
 * The containers Divo will read.
 *
 * ffmpeg downstream handles far more than these three, so this is a policy
 * list rather than a capability limit — kept narrow because every entry is a
 * format we are claiming to have thought about, not merely one that decodes.
 */
const VIDEO_MIME_EXTENSIONS: ReadonlyMap<string, string> = new Map([
  ['video/mp4', 'mp4'],
  ['video/quicktime', 'mov'],
  ['video/webm', 'webm'],
]);

export function isSupportedConversationVideoMime(mimeType: string): boolean {
  return VIDEO_MIME_EXTENSIONS.has(mimeType.toLowerCase());
}

export function extensionForVideoMime(mimeType: string): string {
  return VIDEO_MIME_EXTENSIONS.get(mimeType.toLowerCase()) ?? 'mp4';
}
